parameters:
- name: artifactName  
  type: string
  default: 'onnxruntime-linux-x64-gpu-tensorrt-$(OnnxRuntimeVersion)'

- name: artifactNameNoVersionString
  type: string
  default: 'onnxruntime-linux-x64-gpu-tensorrt'

- name: buildJava
  type: boolean
  default: false

- name: buildJavaOption
  type: string
  default: ''

- name: buildNodejs
  type: boolean
  default: true

- name: buildNodejsOption
  type: string
  default: ''

- name: CudaVersion
  displayName: CUDA version
  type: string
  default: '11.8'
  values:
    - 11.8
    - 12.2



# We only have CUDA/TRT on x64. We do not have a build for CUDA/TRT for ARM64.
# Therefore this file does not have an `OnnxruntimeNodejsBindingArch` parameter
  
stages:
- template: stages/nuget-linux-tensorrt-packaging-stage.yml
  parameters:
    artifactName: ${{ parameters.artifactName }}
    artifactNameNoVersionString: ${{ parameters.artifactNameNoVersionString }}
    buildJava: ${{ parameters.buildJava }}
    buildJavaOption: ${{ parameters.buildJavaOption }}
    buildNodejs: ${{ parameters.buildNodejs }}
    buildNodejsOption: ${{ parameters.buildNodejsOption }}
    CudaVersion: ${{ parameters.CudaVersion }}
